#!/bin/bash
#PBS -N gps_skyplot
#PBS -P eos_ehill
#PBS -l walltime=120:00:00,nodes=1,ncpus=1
#PBS -m n
#PBS -q q32

# unused pbs options:
# specify queue name:
# specify notification email:
# #PBS -M elindsey@ntu.edu.sg

module load ghostscript/9.26
cd $PBS_O_WORKDIR

# cannot do all files at once - too many for the command line! Go one site at a time:
for site in `ls -d /tgo/GPS_DATA/20*/*/???? |awk -F/ '{print $6}' |sort |uniq`
do
  ./make_snr_plots.sh /tgo/GPS_DATA/20*/*/$site/RINEX2/*
done
